# Generated by Django 6.0.6 on 2026-07-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nomba_wallet_id',
        ),
        migrations.AddField(
            model_name='user',
            name='nomba_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='nomba_account_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='nomba_bank_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
