# Generated by Django 6.0.6 on 2026-07-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_nomba_wallet_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nomba_account_holder_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
