# Generated by Django 6.0.6 on 2026-07-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_evidence', models.TextField(blank=True)),
                ('seller_evidence', models.TextField(blank=True)),
                ('ai_ruling', models.JSONField(blank=True, help_text='{"ruling": "buyer|seller|split", "split_ratio": "...", "reasoning": "..."}', null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('awaiting_seller', 'Awaiting Seller Evidence'), ('awaiting_buyer', 'Awaiting Buyer Evidence'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dispute',
                'verbose_name_plural': 'Disputes',
                'ordering': ['-created_at'],
            },
        ),
    ]
