# Generated by Django 6.0.6 on 2026-07-01 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disputes', '0001_initial'),
        ('escrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='agreement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='escrow.escrowagreement'),
        ),
    ]
