# Generated by Django 6.0.6 on 2026-07-01 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disputes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='raised_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raised_disputes', to=settings.AUTH_USER_MODEL),
        ),
    ]
