# Generated by Django 6.0.6 on 2026-07-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=5)),
                ('raw_conditions', models.TextField(help_text='Original plain-language input from the user.')),
                ('conditions', models.JSONField(default=list, help_text='AI-parsed structured milestones (list of milestone dicts).')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('pending_proof', 'Pending Proof'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('refunded', 'Refunded')], db_index=True, default='draft', max_length=20)),
                ('deadline', models.DateTimeField()),
                ('nomba_transaction_ref', models.CharField(blank=True, max_length=200)),
                ('ai_verdict', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Escrow Agreement',
                'verbose_name_plural': 'Escrow Agreements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_met', models.BooleanField(default=False)),
                ('proof_url', models.URLField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ai_confidence', models.IntegerField(blank=True, null=True)),
                ('ai_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
