# Generated by Django 6.0.6 on 2026-07-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowagreement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_payment', 'Awaiting Payment'), ('active', 'Active'), ('pending_proof', 'Pending Proof'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('refunded', 'Refunded')], db_index=True, default='draft', max_length=20),
        ),
    ]
