# Generated by Django 6.0.6 on 2026-07-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0003_alter_escrowagreement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='proof_description',
            field=models.TextField(blank=True),
        ),
    ]
